# Use the official Node.js image as the base image
FROM node:latest

# Set the working directory inside the container
WORKDIR /app

# Copy the frontend source code into the container
COPY /frontend .

# Install dependencies and build the frontend application
RUN npm install && npm run build

# Expose the frontend port
EXPOSE 8080

# Command to run the frontend application
CMD ["npm", "run", "serve"]